pipeline
    {
        agent any
        stages {
            stage ('Build') {
                steps{
                    echo 'Building Spring maven project'
                    withMaven(maven: 'maven_3_8_1') {
                        sh 'mvn -f manipulandoXMLs/pom.xml clean install -X -Denv=stage -Dmeta.filter=groovy:!skip'
                    }
                }
            }
        }
    }