pipeline
    {
        agent none
        stages {
            stage ('Build') {
                git url: 'https://github.com/QALair/Marshal'
                withMaven {
                    sh "mvn clean install"
                }
            }
        }
    }